# To run this requests use the extension for VSCODE named: REST Client
# VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### Return the hotels in json
GET http://localhost:5000/hotels

### Return the hotel by id (bravo)
GET http://localhost:5000/hotels/bravo

### Create the hotel (delta)
POST http://localhost:5000/hotels/delta
content-type: application/json

{
    "name": "Delta Hotel",
    "stars": 4.9,
    "diary": 720.2,
    "city": "New York"
}
###

### Update hotel (bravo)
PUT http://localhost:5000/hotels/bravo
content-type: application/json

{
    "name": "Bravo ALTERADO Hotel",
    "stars": 4.4,
    "diary": 420.34,
    "city": "Los Angeles"
}
###


### Create hotel with HTTP method PUT (if not exists)
PUT http://localhost:5000/hotels/echo
content-type: application/json

{
    "name": "Echo Hotel",
    "stars": 4.0,
    "diary": 410.2,
    "city": "Washington"
}
###

### Delete hotel by hotel_id
DELETE http://localhost:5000/hotels/echo